#!/usr/bin/env bash
set -e

echo "Checking Code Style"

sleep 2

echo "api"
(cd api || exit;  npm run lint-no-fix)

sleep 1

echo "frontend"
(cd frontend || exit; npm run lint-no-fix)

echo "no errors found."
