version: '3.3'
volumes:
  database_volume: {}

networks:
  default: {}
  public:
    external: true
  dbs_network:
    external: true

services:
  api:
    build:
      context: .
      dockerfile: .devops/docker/api/Dockerfile
    env_file: .env
    networks:
      - default
    volumes:
      - ./api:/app
      - ./.devops/docker/api/config/entrypoint.sh:/usr/local/bin/entrypoint.sh
    working_dir: /app

  frontend:
    build:
      context: .
      dockerfile: .devops/docker/frontend/Dockerfile
    env_file: .env
    networks:
      - default
    volumes:
      - ./frontend:/app
    working_dir: /app

  proxy:
    build:
      context: .
      dockerfile: .devops/docker/proxy/Dockerfile
    depends_on:
      - api
      - frontend
    env_file: .env
    labels:
      - traefik.backend=dbs-acoustic-rating
      - traefik.frontend.rule=Host:dev.dbs-acoustic-rating.docker
      - traefik.docker.network=public
      - traefik.port=80
    networks:
      default:
        aliases:
          - dev.dbs-acoustic-rating.docker
      public: {}
      dbs_network:
        aliases:
          - dbs-acoustic-rating
    volumes:
      - ./api/static:/app/api/v1/static
