version: '3.3'

networks:
  default: {}
  dbs_network:
    external: true

services:
  api:
    build:
      context: .
      dockerfile: .devops/docker/service/Dockerfile
    environment:
      - MAX_FILE_SIZE=20000000
    networks:
      default: {}
      dbs_network:
        aliases:
          - acoustic-rating-service
    volumes:
      - ./api:/app
    ports:
      - "8111:8111"

  frontend:
    build:
      context: .
      dockerfile: .devops/docker/gui/Dockerfile.local
    networks:
      default:
        aliases:
          - dev.acoustic-rating-app.docker
    volumes:
      - ./frontend:/app
    ports:
      - "8110:8110"
