version: '3.3'
volumes:
  database_volume: {}

networks:
  default: {}
  public:
    external: true
  dbs_network:
    external: true

services:
  api:
    build:
      context: .
      dockerfile: .devops/docker/api/Dockerfile
    environment:
      - MAX_FILE_SIZE=20000000
    networks:
      - default
    volumes:
      - ./api:/app
    ports:
      - "8111:8111"
    working_dir: /app

  frontend:
    build:
      context: .
      dockerfile: .devops/docker/frontend/Dockerfile
    networks:
      default:
        aliases:
          - dev.dbs-acoustic-rating.docker
      dbs_network:
        aliases:
          - dbs-acoustic-rating
    volumes:
      - ./frontend:/app
    ports:
      - "8110:8110"
    working_dir: /app
