version: '3.3'

networks:
  default: {}
  dbs_network:
    external: true

services:
  api:
    build:
      context: .
      dockerfile: .devops/docker/api/Dockerfile
    environment:
      - MAX_FILE_SIZE=20000000
    networks:
      - default
      - dbs_network
    volumes:
      - ./api:/app
    ports:
      - "8111:8111"
    working_dir: /app

  frontend:
    build:
      context: .
      dockerfile: .devops/docker/frontend/Dockerfile
    networks:
      default:
        aliases:
          - dev.acoustic-rating-app.docker
      dbs_network:
        aliases:
          - acoustic-rating-app
    volumes:
      - ./frontend:/app
    ports:
      - "8110:8110"
    working_dir: /app
